### ISSUE TITLE
ShadowVPN已经删除了， 还有其它的解决方案吗？

### ISSUE THREAD

**Issue by chasel** [OkamiChen/VPN-traffic-redirect-to-another-vpn-tunnel#1]
另外openvpn和ShadowVPN是安装在同一台服务器吗？
那shadowvpn他是怎么和国外的vps连接到一起的， 这一块没看懂， 能指点下吗？

**Comment by littlewolf9527** [comment]
国内的机子s和o都要装。
安装过程：[点这里](https://kyonli.com/p/75)
你可以在Github上找到这个开源软件的Fork。

**Comment by chasel** [comment]
我梳理一下， 整个流程是这样的吗？ 国外的vps安装s的服务端，国内的服务器安装o的服务端和s的客户端， s客户端连接上国外的s服务端， 自己本地的机器用o的客户端连接国内o的服务端， 在国内的服务器上做做一个s和o的转发。这个过程是否正确？

**Comment by littlewolf9527** [comment]
y

**Comment by chasel** [comment]
![slack-imgs com](https://cloud.githubusercontent.com/assets/1614604/12084934/e016f818-b2f4-11e5-8fc7-81443e2674a1.png)
画了张图， 怕说不清楚. 
这是我的理解。

**Comment by littlewolf9527** [comment]
u r right :)

2016-01-04 15:08 GMT+08:00 chasel notifications@github.com:

**Comment by chasel** [comment]
你好， 我发现安装shadowvpn后， 并没有看到
sudo route add -host 8.8.8.8 dev tunX （tunX是你ShadowVPN的interface） 
这句话所说的tunx， 怎么才能看到它呢？ 麻烦指点一下， 下面我具体环境的信息
![screenshot from 2016-01-10 14 05 21](https://cloud.githubusercontent.com/assets/1614604/12220218/722e4b72-b7a3-11e5-84d0-7f126db504aa.png)

**Comment by chasel** [comment]
然后我在我的client_up.sh文件中也没有发现这一段配置， 没有发现是否有影响。

> echo changing default route  
> if [ pppoe-wan = "$old_gw_intf" ]; then  
> route add $server $old_gw_intf  
> else  
> route add $server gw $old_gw_ip  
> fi  
> route del default  
> route add default gw 10.7.0.1  
> echo default route changed to 10.7.0.1  

我自己的配置是这样的

> ##### Turn on IP forwarding
> 
> sysctl -w net.ipv4.ip_forward=1

#### Configure IP address and MTU of VPN interface

ip addr add $net dev $intf
ip link set $intf mtu $mtu
ip link set $intf up

#### Turn on NAT over VPN

iptables -t nat -A POSTROUTING -o $intf -j MASQUERADE
iptables -I FORWARD 1 -i $intf -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD 1 -o $intf -j ACCEPT

#### Direct route to VPN server's public IP via current gateway

ip route add $server via $(ip route show 0/0 | sed -e 's/.\* via ([^ ]_)._/\1/')

#### Shadow default route using two /1 subnets

ip route add   0/1 dev $intf
ip route add 128/1 dev $intf

echo $0 done

如果需要改动应该怎么改动呢？

**Comment by littlewolf9527** [comment]
我的意思就是tun\* ，就是你shadowvpn产生的tun网卡
顺便shadowvpn的tun网卡最好不要设置tun0，容易和其他软件的冲突导致shadowvpn启动失败

2016-01-10 14:12 GMT+08:00 chasel notifications@github.com:

**Comment by chasel** [comment]
tun0不是shadowvpn产生的网卡， 是openvpn生成的网卡, shadowvpn没有产生网卡， 所以我才问的。

**Comment by chasel** [comment]
我按照你的教程执行到这一步的时候， 发生了这个

> nslookup twitter.com 8.8.8.8
> ;; connection timed out; no servers could be reached

该如何解决呢？
忽略它之后， 我继续走下去， 最后发现还是无法完成隧道嫁接， 最终结果还是无法连接到国外的服务器上， 该怎么排查到底是哪一步出问题了呢？

**Comment by littlewolf9527** [comment]
你先查路由连通啊，先看看隧道通了没，应该是因为隧道没起来导致的，server端正确配置了没？端口开了没？

**Comment by littlewolf9527** [comment]
所以说我让你把shadowvpn的网卡设置成非tun0

2016-01-10 18:03 GMT+08:00 chasel notifications@github.com:

**Comment by chasel** [comment]
我设置成非0了， 然后通过该教程 https://github.com/clowwindy/ShadowVPN/wiki/FAQ 描述的步骤排查问题， 都正确， 但是发现连接后， 客户端这边是上不了外网？服务端vps是正常可以上网的。有什么办法可以解决呢？

**Comment by littlewolf9527** [comment]
应该是脚本里面激活NAT的语句没成功执行，你自己写一下NAT语句就好。

在 2016年1月18日 下午1:52，chasel notifications@github.com写道：

**Comment by chasel** [comment]
我还没有做隧道接入， 只是在本地和国外的vps安装了shadowvpn， 连通后发现无法上网， 是不是shadowvpn还需要配置些什么？

**Comment by littlewolf9527** [comment]
没有路由表，没有防火墙配置，无法定位问题。

2016-01-19 13:54 GMT+08:00 chasel notifications@github.com:
